name: Build_Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

      - name: Deploy to Staging
        uses: easingthemes/ssh-deploy@v2.2.3
        with:
          server: ${{ secrets.STAGING_SERVER }}
          username: ${{ secrets.STAGING_USERNAME }}
          password: ${{ secrets.STAGING_PASSWORD }}
          source: './target/my-web-app.war'
          target: '/opt/tomcat/webapps'
