# GIT STUFF

name: Git Settings

on:
  workflow_dispatch:

jobs:
    git-set-commit:
        name: Git Settings and Commit
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout do repositório
            uses: actions/checkout@v2 
            with: 
              repository: ${{ github.repository }}
          
          - name: Configurar usuário Git
            run: |
              git config --global user.name "GitHub Actions"
              git config --global user.email "${{ secrets.USER_NAME }}"
              git config --global credential.helper store
              echo "https://github.com:${{ secrets.ACCESS_TOKEN }}@github.com" >> ~/.git-credentials

          - name: Commit e push das alteracoes
            run: |
              git add .
              git status
              git commit -v -m "Add badge to readme"
              git push -v

          